"""Tests for run_metadata module and its integration into the CLI pipeline.

Verifies:
  1. get_app_version returns a non-empty string
  2. build_run_metadata captures all required fields
  3. Mapping values are recorded correctly (including absent address col)
  4. save_run_metadata writes valid JSON with all required keys
  5. run_metadata.json is generated by the full pipeline (via cluster_suppliers)
  6. final_supplier_clustered.csv columns are unchanged (no internal columns leak)
  7. Smoke check does not crash when B LAB rows are present
  8. Smoke check is a no-op when no B LAB rows are present
"""
import json
import os
import tempfile

import polars as pl
import pytest

from src.config import ClusteringConfig
from src.main import cluster_suppliers
from src.preprocessing import preprocess_dataframe
from src.run_metadata import (
    build_run_metadata,
    get_app_version,
    save_run_metadata,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _minimal_config() -> ClusteringConfig:
    cfg = ClusteringConfig()
    cfg.llm_enabled = False
    cfg.llm_execution_mode = "disabled"
    return cfg


def _minimal_mapping() -> dict:
    return {
        "supplier_name": "CommonName",
        "address": "Address Line 1",
        "city": "Supplier Origin City",
        "country": "Supplier Origin Country",
        "postal_code": "Supplier Origin Postal",
    }


def _b_lab_df() -> pl.DataFrame:
    return pl.DataFrame({
        "CommonName": ["B LAB CO.", "B LAB COMPANY", "UNRELATED CORP INC"],
        "Address Line 1": ["15 WATERLOO AVE", "15 WATERLOO AVE", "999 OTHER ST"],
        "Supplier Origin City": ["BERWYN", "BERWYN", "CHICAGO"],
        "Supplier Origin Country": ["US", "US", "US"],
        "Supplier Origin Postal": ["19312", "19312", "60601"],
    })


# ---------------------------------------------------------------------------
# Test 1: get_app_version always returns a non-empty string
# ---------------------------------------------------------------------------

class TestGetAppVersion:
    def test_returns_non_empty_string(self):
        version = get_app_version()
        assert isinstance(version, str)
        assert len(version) > 0, "get_app_version must return a non-empty string"

    def test_returns_str_not_none(self):
        version = get_app_version()
        assert version is not None


# ---------------------------------------------------------------------------
# Test 2: build_run_metadata captures all required fields
# ---------------------------------------------------------------------------

class TestBuildRunMetadata:
    def test_required_keys_present(self):
        config = _minimal_config()
        meta = build_run_metadata(
            mapping=_minimal_mapping(),
            input_row_count=100,
            config=config,
        )
        required = [
            "app_commit_hash", "app_version", "run_timestamp",
            "input_row_count",
            "mapped_supplier_name", "mapped_address",
            "mapped_city", "mapped_country", "mapped_postal_code",
            "mapped_email", "mapped_tax_id", "mapped_website",
            "ignore_client_domains", "show_70_candidates",
            "llm_mode", "review_output_enabled", "audit_output_enabled",
        ]
        for key in required:
            assert key in meta, f"run_metadata missing required key: {key!r}"

    def test_mapping_values_recorded_correctly(self):
        config = _minimal_config()
        mapping = _minimal_mapping()
        meta = build_run_metadata(mapping=mapping, input_row_count=42, config=config)
        assert meta["mapped_supplier_name"] == "CommonName"
        assert meta["mapped_address"] == "Address Line 1"
        assert meta["mapped_city"] == "Supplier Origin City"
        assert meta["mapped_country"] == "Supplier Origin Country"
        assert meta["mapped_postal_code"] == "Supplier Origin Postal"
        assert meta["input_row_count"] == 42

    def test_missing_address_column_recorded_as_empty(self):
        """If no address column is in the mapping, mapped_address must be ''."""
        config = _minimal_config()
        mapping = {"supplier_name": "CommonName", "country": "Country"}
        meta = build_run_metadata(mapping=mapping, input_row_count=10, config=config)
        assert meta["mapped_address"] == "", (
            f"Expected mapped_address='', got {meta['mapped_address']!r}"
        )

    def test_app_version_non_empty(self):
        config = _minimal_config()
        meta = build_run_metadata(mapping={}, input_row_count=0, config=config)
        assert meta["app_version"], "app_version must be non-empty"

    def test_ignore_domains_serialised_as_sorted_list(self):
        config = _minimal_config()
        config.ignore_client_domains = frozenset({"zebra.com", "apple.com"})
        meta = build_run_metadata(mapping={}, input_row_count=0, config=config)
        assert isinstance(meta["ignore_client_domains"], list)
        assert meta["ignore_client_domains"] == sorted(["zebra.com", "apple.com"])

    def test_show_70_candidates_is_bool(self):
        """show_70_candidates must be a bool (not None, not a string)."""
        config = _minimal_config()
        meta = build_run_metadata(mapping={}, input_row_count=0, config=config)
        assert isinstance(meta["show_70_candidates"], bool)

    def test_show_70_candidates_reflects_config(self):
        """show_70_candidates value must match what was set in config."""
        config = _minimal_config()
        config.allow_unresolved_llm_candidates_in_final_output = False
        meta_off = build_run_metadata(mapping={}, input_row_count=0, config=config)
        assert meta_off["show_70_candidates"] is False

        config.allow_unresolved_llm_candidates_in_final_output = True
        meta_on = build_run_metadata(mapping={}, input_row_count=0, config=config)
        assert meta_on["show_70_candidates"] is True


# ---------------------------------------------------------------------------
# Test 3: save_run_metadata writes valid JSON
# ---------------------------------------------------------------------------

class TestSaveRunMetadata:
    def test_writes_valid_json(self, tmp_path):
        config = _minimal_config()
        meta = build_run_metadata(
            mapping=_minimal_mapping(), input_row_count=5, config=config
        )
        path = str(tmp_path / "run_metadata.json")
        save_run_metadata(meta, path)
        assert os.path.isfile(path)
        with open(path) as fh:
            loaded = json.load(fh)
        assert loaded["mapped_supplier_name"] == "CommonName"
        assert loaded["mapped_address"] == "Address Line 1"
        assert loaded["input_row_count"] == 5

    def test_creates_parent_directories(self, tmp_path):
        config = _minimal_config()
        meta = build_run_metadata(mapping={}, input_row_count=0, config=config)
        nested = str(tmp_path / "a" / "b" / "c" / "run_metadata.json")
        save_run_metadata(meta, nested)
        assert os.path.isfile(nested)


# ---------------------------------------------------------------------------
# Test 4: run_metadata.json generated alongside final output (pipeline-level)
# ---------------------------------------------------------------------------

class TestRunMetadataPipelineGeneration:
    def test_run_metadata_generated_in_output_dir(self, tmp_path):
        """After cluster_suppliers, saving run_metadata produces a valid file."""
        df = _b_lab_df()
        mapping = _minimal_mapping()
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        meta = build_run_metadata(
            mapping=mapping,
            input_row_count=len(df),
            config=config,
        )
        meta_path = str(tmp_path / "run_metadata.json")
        save_run_metadata(meta, meta_path)
        assert os.path.isfile(meta_path)
        with open(meta_path) as fh:
            loaded = json.load(fh)
        assert loaded["mapped_supplier_name"] == "CommonName"
        assert loaded["mapped_address"] == "Address Line 1"
        assert loaded["input_row_count"] == 3

    def test_run_metadata_timestamp_is_iso_string(self, tmp_path):
        config = _minimal_config()
        meta = build_run_metadata(mapping={}, input_row_count=0, config=config)
        meta_path = str(tmp_path / "meta.json")
        save_run_metadata(meta, meta_path)
        with open(meta_path) as fh:
            loaded = json.load(fh)
        ts = loaded["run_timestamp"]
        assert "T" in ts, f"Expected ISO timestamp, got {ts!r}"


# ---------------------------------------------------------------------------
# Test 5: final_supplier_clustered.csv columns are unchanged
# ---------------------------------------------------------------------------

class TestFinalOutputColumnsUnchanged:
    def test_no_internal_columns_leak_into_main_df(self):
        """cluster_suppliers must not add any columns beyond original + Cluster Number + Match Percentage."""
        df = _b_lab_df()
        mapping = _minimal_mapping()
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        main_df = result["main_df"]
        input_cols = set(df.columns)
        allowed_extra = {"Cluster Number", "Match Percentage"}
        extra_cols = set(main_df.columns) - input_cols - allowed_extra
        assert not extra_cols, (
            f"Internal columns leaked into main_df: {extra_cols}"
        )

    def test_main_df_has_correct_column_order_prefix(self):
        """Original columns must precede Cluster Number and Match Percentage."""
        df = _b_lab_df()
        mapping = _minimal_mapping()
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        cols = result["main_df"].columns
        # Original input columns must all be present
        for c in df.columns:
            assert c in cols, f"Original column {c!r} missing from main_df"


# ---------------------------------------------------------------------------
# Test 6: smoke check does not crash on B LAB rows
# ---------------------------------------------------------------------------

class TestSmokeCheckBLab:
    def test_smoke_check_does_not_crash_with_b_lab_rows(self, capsys):
        """_smoke_check_b_lab must complete without raising when B LAB rows present."""
        from scripts.run_cli import _smoke_check_b_lab

        df = _b_lab_df()
        mapping = _minimal_mapping()
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        # Should not raise
        _smoke_check_b_lab(result, mapping)
        captured = capsys.readouterr()
        # Must print at least one [SMOKE] line
        assert "[SMOKE]" in captured.out, (
            "Expected [SMOKE] lines in stdout when B LAB rows are present"
        )

    def test_smoke_check_noop_without_b_lab_rows(self, capsys):
        """_smoke_check_b_lab must be silent when no B LAB rows are present."""
        from scripts.run_cli import _smoke_check_b_lab

        df = pl.DataFrame({
            "Supplier Name": ["ACME CORP INC", "GLOBAL TECH LLC"],
            "Address": ["100 MAIN ST", "200 BROADWAY"],
            "Country": ["US", "US"],
        })
        mapping = {"supplier_name": "Supplier Name", "address": "Address", "country": "Country"}
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        _smoke_check_b_lab(result, mapping)
        captured = capsys.readouterr()
        assert "[SMOKE]" not in captured.out, (
            "Smoke check must not print when no B LAB rows are present"
        )

    def test_smoke_check_reports_cluster_outcome(self, capsys):
        """Smoke check must report whether B LAB rows ended up in the same cluster."""
        from scripts.run_cli import _smoke_check_b_lab

        df = _b_lab_df()
        mapping = _minimal_mapping()
        config = _minimal_config()
        result = cluster_suppliers(df, mapping, config)
        _smoke_check_b_lab(result, mapping)
        captured = capsys.readouterr()
        # Must contain either a success or failure indicator
        assert ("✅ Clustered together" in captured.out or
                "❌ B LAB rows NOT" in captured.out), (
            f"Smoke check must report cluster outcome. Got:\n{captured.out}"
        )
